# version: '3'
# services:
#   laravel-franken:
#     container_name: festix_franken_sqlite
#     image: image_festix_franken_sqlite
#     build: .
#     ports:
#       - "8000:80"
#     env_file:
#       - .env
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel-app
#     volumes:
#       - .:/var/www
#     ports:
#       - "8000:80"
#     env_file:
#       - .env
#     networks:
#       - laravel-net

#   nginx:
#     image: nginx:stable-alpine
#     container_name: nginx-laravel
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www
#       - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     networks:
#       - laravel-net

# networks:
#   laravel-net:
#     driver: bridge

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aorus22/rently-backend:v3
    container_name: rently-backend
    restart: always
    working_dir: /var/www/
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - .:/var/www


# version: '3.8'

# services:
#   app:
#     image: laravel-franken:latest
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/app
#     env_file:
#       - .env

